---
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  http_forwarder:
    ingress:
      endpoint: 0.0.0.0:6060
    egress:
      endpoint: "https://api.${SPLUNK_REALM}.signalfx.com"
  zpages: {}
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  sapm:
    endpoint: 0.0.0.0:7276
  signalfx:
    endpoint: 0.0.0.0:9943

  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu: {}
      disk: {}
      load: {}
      filesystem: {}
      memory: {}
      network: {}
      paging: {}
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
      processes: {}
  prometheus:
    config:
      global:
        scrape_interval: 60s
      scrape_configs:
        - job_name: otel-collector-binary
          static_configs:
            - targets:


processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    system:
      hostname_sources: [os]

exporters:
  otlphttp:
    traces_endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace/otlp"
    headers:
      "X-SF-Token": "${SPLUNK_ACCESS_TOKEN}"
  # Metrics
  signalfx:
    # TODO: Ensure this is set properly
    # access_token: "${SPLUNK_ACCESS_TOKEN}"
    # TODO: Ensure this is set properly
    # realm: "${SPLUNK_REALM}"
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    api_url: "${SPLUNK_API_URL}"
    ingest_url: "${SPLUNK_INGEST_URL}"
    sync_host_metadata: true
  # Logs (can also be used to send traces)
  #  otlp:
  #    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
  #    tls:
  #      insecure: false
  #    headers:
  #      "signoz-access-token": ${SIGNOZ_INGESTION_KEY}
#  debug:
#    verbosity: normal


service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  extensions: [health_check, http_forwarder, zpages]


  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [signalfx]
    metrics/internal:
      receivers: [prometheus, signalfx, hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [signalfx]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, signalfx]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [signalfx]
